name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.x.x # use the explicit version number
        with:
         command: npm run ui-regression
      - name: Cypress run Uploading artefact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
      - name: Slack Notifi creation
        uses: rtCamp/action-slack-notify@v2
        env:        
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Szwedzki Kucharz
          SLACK_ICON: https://bit.ly/3xw14Sk
          SLACK_TITLE: Post Title
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
