Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@paler44 
JoanEsquivel
/
cypress-reports
Public
Fork your own copy of JoanEsquivel/cypress-reports
Code
Issues
Pull requests
Actions
Projects
Security
Insights
Beta Try the new code view
cypress-reports/.github/workflows/demo.yml
@JoanEsquivel
JoanEsquivel Update demo.yml
Latest commit 8b0d9a8 on Oct 9, 2022
 History
 1 contributor
31 lines (29 sloc)  919 Bytes
 

name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          command: npm run ui-regression
      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: joanmedia
          SLACK_TITLE: Regression Test
          SLACK_MESSAGE: "New changes :rocket:"
          SLACK_COLOR: ${{ job.status }}
