name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctlys
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4 # use the explicit version numberr
        with:
          install: npm install
          start: npm start
          command: npm run ui-regression
      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: szwedzkiKucharz
          SLACK_ICON: https://bit.ly/3xw14Sk
          SLACK_TITLE: Smaczne Testy
          SLACK_MESSAGE: " @here Den är grön :cook:"
          SLACK_COLOR: ${{ job.status }}
